spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/logisticSystem
    username:
    password:
  data:
    redis:
      port: 6379
      host: localhost

jwt:
  enabled: true
  header: Authorization
  expire: 21600
  secret: this is a secret