server:
  port: 2333
  tomcat:
    max-http-form-post-size: 30KB

info:
  title: Logistics Center API
  description: Logistics Backend Center
  version: ${version?:unknown}

spring:
  profiles:
    active: dev
  jackson:
    property-naming-strategy: SNAKE_CASE
    time-zone: GMT+8
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  file:
    name: ./logs/latest.log
  logback:
    rollingpolicy:
      max-history: 14
      clean-history-on-start: true

cache:
  default-expire: 60

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
  packages-to-scan: cn.anselyuki