version: '3.8'
services:
  redis:
    networks:
      - default
    image: redis:latest
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
  mysql:
    networks:
      - default
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 18670054724
      MYSQL_DATABASE: logisticSystem
    ports:
      - "3307:3306"
    restart: always
  logistics_backend:
    networks:
      - default
    build:
      context: ../
      dockerfile: dockerfile
    container_name: Logistics-backend
    command: --spring.profiles.active=prod
    ports:
      - "2333:2333"
    links:
      - redis
      - mysql
    restart: always
    depends_on:
      - redis
      - mysql