version: '3.8'
services:
  redis:
    image: redis:latest
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
  mongo:
    image: mysql:latest
    container_name: mysql
    volumes:
      - ../.data:/data/db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 18670054724
      MYSQL_DATABASE: LogisticsSystem
    restart: always
  maa:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: Logistics Backend
    command: --spring.profiles.active=prod
    ports:
      - "2333:2333"
    volumes:
      - ./application-prod.yml:/app/application-prod.yml:ro
    links:
      - redis
      - mysql
    restart: always
    depends_on:
      - redis
      - mysql